# Generated by Django 4.0.3 on 2022-03-28 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='footer',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
